/**
 * Acciones de auditoría (seguridad + negocio).
 * Convención: MAYÚSCULAS_SNAKE; metadata solo IDs, títulos cortos y flags (evitar PII denso).
 */
export const SECURITY_AUDIT_ACTION = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED_CREDENTIALS: 'AUTH_LOGIN_FAILED_CREDENTIALS',
  AUTH_LOGIN_BLOCKED_INACTIVE: 'AUTH_LOGIN_BLOCKED_INACTIVE',

  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_CHANGE_REJECTED: 'PASSWORD_CHANGE_REJECTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  ADMIN_COLLABORATOR_CREATED: 'ADMIN_COLLABORATOR_CREATED',
  ADMIN_COLLABORATOR_ACTIVATED: 'ADMIN_COLLABORATOR_ACTIVATED',
  ADMIN_COLLABORATOR_DEACTIVATED: 'ADMIN_COLLABORATOR_DEACTIVATED',

  COLLABORATOR_PROFILE_SHEET_UPDATED: 'COLLABORATOR_PROFILE_SHEET_UPDATED',

  FORM_DEFINITION_CREATED: 'FORM_DEFINITION_CREATED',
  FORM_PUBLISHED: 'FORM_PUBLISHED',
  FORM_CLOSED: 'FORM_CLOSED',
  FORM_UNPUBLISHED: 'FORM_UNPUBLISHED',
  FORM_DUPLICATED: 'FORM_DUPLICATED',
  FORM_RESPONSE_SUBMITTED: 'FORM_RESPONSE_SUBMITTED',

  /** Acreditación de jikkopuntos por respuesta a formulario (actor = beneficiario). */
  JIKKOPOINTS_FORM_REWARD_CREDITED: 'JIKKOPOINTS_FORM_REWARD_CREDITED',

  /** Cargo de jikkopuntos por canje administrado (descanso, etc.); metadata con coste y tipo. */
  JIKKOPOINTS_ADMIN_REDEEM_DEBITED: 'JIKKOPOINTS_ADMIN_REDEEM_DEBITED',

  /** Canje de beneficio por colaborador (adjunto autorización jefe). */
  JIKKOPOINTS_BENEFIT_REDEEMED: 'JIKKOPOINTS_BENEFIT_REDEEMED',

  REDEMPTION_REQUESTED: 'REDEMPTION_REQUESTED',
  REDEMPTION_APPROVED: 'REDEMPTION_APPROVED',
  REDEMPTION_REJECTED: 'REDEMPTION_REJECTED',

  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
} as const;

export type PasswordChangeRejectReason =
  | 'WRONG_CURRENT'
  | 'POLICY_VIOLATION'
  | 'REUSED_PASSWORD'
  | 'MISMATCH_CONFIRM'
  | 'SAME_AS_CURRENT';
