export const NOTIFICATION_TYPE = {
  FORM_PUBLISHED: 'FORM_PUBLISHED',
  REDEMPTION_PENDING: 'REDEMPTION_PENDING',
  REDEMPTION_APPROVED: 'REDEMPTION_APPROVED',
  REDEMPTION_REJECTED: 'REDEMPTION_REJECTED',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  JP_BALANCE_CREDIT: 'JP_BALANCE_CREDIT',
} as const;
