import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import * as bcrypt from 'bcrypt';
import { ROLE_CODES } from '../../common/constants/roles';
import { SECURITY_AUDIT_ACTION } from '../../common/security/security-audit.constants';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreateCollaboratorDto } from './dto/create-collaborator.dto';
import { ListCollaboratorsQueryDto } from './dto/list-collaborators-query.dto';
import { UpdateCollaboratorAdminDto } from './dto/update-collaborator-admin.dto';
import { generateTemporaryPassword } from './utils/temp-password';

const userPublicSelect = {
  id: true,
  email: true,
  firstName: true,
  lastName: true,
  idNumber: true,
  idIssueDate: true,
  mustChangePassword: true,
  isActive: true,
  role: { select: { code: true } },
} as const;

const collaboratorAdminSelect = {
  id: true,
  email: true,
  firstName: true,
  lastName: true,
  idNumber: true,
  idIssueDate: true,
  mustChangePassword: true,
  isActive: true,
  createdAt: true,
  updatedAt: true,
  role: { select: { code: true } },
  profile: {
    select: {
      jobTitle: true,
      area: true,
      organizationalDepartment: true,
    },
  },
} satisfies Prisma.UserSelect;

@Injectable()
export class UsersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
  ) {}

  private async collaboratorRoleId(): Promise<string> {
    const role = await this.prisma.role.findUnique({
      where: { code: ROLE_CODES.COLLABORATOR },
    });
    if (!role) {
      throw new NotFoundException(
        'Rol COLABORATOR no configurado; ejecuta el seed',
      );
    }
    return role.id;
  }

  async createCollaborator(dto: CreateCollaboratorDto, actorUserId: string) {
    const email = dto.email.trim().toLowerCase();
    const idNumber = dto.idNumber.trim();
    const [byEmail, byId] = await Promise.all([
      this.prisma.user.findUnique({ where: { email } }),
      this.prisma.user.findUnique({ where: { idNumber } }),
    ]);
    if (byEmail) {
      throw new ConflictException('Ya existe un usuario con ese correo');
    }
    if (byId) {
      throw new ConflictException(
        'Ya existe un usuario con ese número de identificación',
      );
    }
    const roleId = await this.collaboratorRoleId();
    const plainTemp =
      dto.temporaryPassword && dto.temporaryPassword.length > 0
        ? dto.temporaryPassword
        : generateTemporaryPassword();
    const wasAutoGenerated = !(
      dto.temporaryPassword && dto.temporaryPassword.length > 0
    );
    const passwordHash = await bcrypt.hash(plainTemp, 12);
    const jobTitle = dto.jobTitle?.trim() || undefined;
    const area = dto.area?.trim() || undefined;
    const organizationalDepartment =
      dto.organizationalDepartment?.trim() || undefined;

    const user = await this.prisma.$transaction(async (tx) => {
      const u = await tx.user.create({
        data: {
          email,
          passwordHash,
          firstName: dto.firstName.trim(),
          lastName: dto.lastName.trim(),
          idNumber,
          idIssueDate: new Date(dto.idIssueDate),
          mustChangePassword: true,
          isActive: true,
          roleId,
          jikkoAccount: { create: { balance: 0 } },
          profile: {
            create: {
              jobTitle,
              area,
              organizationalDepartment: organizationalDepartment ?? null,
            },
          },
        },
        select: collaboratorAdminSelect,
      });
      await this.audit.logSecurityEventTx(tx, {
        userId: u.id,
        actorUserId,
        action: SECURITY_AUDIT_ACTION.ADMIN_COLLABORATOR_CREATED,
        metadata: {
          email: u.email,
          idNumber: u.idNumber,
          jobTitle: jobTitle ?? null,
          area: area ?? null,
          organizationalDepartment: organizationalDepartment ?? null,
          temporaryPasswordAutoGenerated: wasAutoGenerated,
        },
      });
      return u;
    });

    return {
      ...user,
      ...(wasAutoGenerated ? { temporaryPasswordPlain: plainTemp } : {}),
    };
  }

  async listCollaborators(query: ListCollaboratorsQueryDto) {
    const roleId = await this.collaboratorRoleId();
    const take = query.take ?? 20;
    const skip = query.skip ?? 0;

    const filters: Prisma.UserWhereInput[] = [{ roleId }];

    if (typeof query.isActive === 'boolean') {
      filters.push({ isActive: query.isActive });
    }

    if (query.area?.trim()) {
      filters.push({
        profile: {
          is: { area: { contains: query.area.trim() } },
        },
      });
    }

    if (query.q?.trim()) {
      const term = query.q.trim();
      filters.push({
        OR: [
          { email: { contains: term } },
          { firstName: { contains: term } },
          { lastName: { contains: term } },
          { idNumber: { contains: term } },
        ],
      });
    }

    const where: Prisma.UserWhereInput = { AND: filters };

    const [items, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        select: collaboratorAdminSelect,
        orderBy: { createdAt: 'desc' },
        skip,
        take,
      }),
      this.prisma.user.count({ where }),
    ]);

    return { items, total, skip, take };
  }

  async getCollaboratorAdmin(id: string) {
    const roleId = await this.collaboratorRoleId();
    const user = await this.prisma.user.findFirst({
      where: { id, roleId },
      select: collaboratorAdminSelect,
    });
    if (!user) {
      throw new NotFoundException('Colaborador no encontrado');
    }
    return user;
  }

  async updateCollaboratorAdmin(
    actorUserId: string,
    id: string,
    dto: UpdateCollaboratorAdminDto,
  ) {
    const roleId = await this.collaboratorRoleId();
    const existing = await this.prisma.user.findFirst({
      where: { id, roleId },
      include: { profile: true },
    });
    if (!existing) {
      throw new NotFoundException('Colaborador no encontrado');
    }

    const patchCount = [
      dto.firstName,
      dto.lastName,
      dto.jobTitle,
      dto.area,
      dto.organizationalDepartment,
      dto.isActive,
    ].filter((v) => v !== undefined).length;
    if (patchCount === 0) {
      throw new BadRequestException('No hay campos para actualizar');
    }

    const prevActive = existing.isActive;

    const userData: Prisma.UserUpdateInput = {};
    if (dto.firstName !== undefined) {
      userData.firstName = dto.firstName.trim();
    }
    if (dto.lastName !== undefined) {
      userData.lastName = dto.lastName.trim();
    }
    if (typeof dto.isActive === 'boolean') {
      userData.isActive = dto.isActive;
    }

    const profileData: Prisma.UserProfileUpdateInput = {};
    if (dto.jobTitle !== undefined) {
      profileData.jobTitle = dto.jobTitle.trim() || null;
    }
    if (dto.area !== undefined) {
      profileData.area = dto.area.trim() || null;
    }
    if (dto.organizationalDepartment !== undefined) {
      profileData.organizationalDepartment = dto.organizationalDepartment;
    }
    const hasProfilePatch = Object.keys(profileData).length > 0;
    const hasUserPatch = Object.keys(userData).length > 0;

    await this.prisma.$transaction(async (tx) => {
      if (hasUserPatch) {
        await tx.user.update({ where: { id }, data: userData });
      }
      if (hasProfilePatch) {
        await tx.userProfile.upsert({
          where: { userId: id },
          create: {
            userId: id,
            jobTitle:
              dto.jobTitle !== undefined
                ? dto.jobTitle.trim() || null
                : null,
            area: dto.area !== undefined ? dto.area.trim() || null : null,
            organizationalDepartment:
              dto.organizationalDepartment !== undefined
                ? dto.organizationalDepartment
                : null,
          },
          update: profileData,
        });
      }

      if (
        typeof dto.isActive === 'boolean' &&
        dto.isActive === false &&
        prevActive
      ) {
        await tx.refreshToken.updateMany({
          where: { userId: id, revokedAt: null },
          data: { revokedAt: new Date() },
        });
        await this.audit.logSecurityEventTx(tx, {
          userId: id,
          actorUserId,
          action: SECURITY_AUDIT_ACTION.ADMIN_COLLABORATOR_DEACTIVATED,
          metadata: { previousIsActive: prevActive },
        });
      } else if (
        typeof dto.isActive === 'boolean' &&
        dto.isActive === true &&
        !prevActive
      ) {
        await this.audit.logSecurityEventTx(tx, {
          userId: id,
          actorUserId,
          action: SECURITY_AUDIT_ACTION.ADMIN_COLLABORATOR_ACTIVATED,
          metadata: { previousIsActive: prevActive },
        });
      }
    });

    return this.getCollaboratorAdmin(id);
  }

  async getMe(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: userPublicSelect,
    });
    if (!user) {
      throw new NotFoundException('Usuario no encontrado');
    }
    return user;
  }
}
